// Mocks generated by Mockito 5.4.6 from annotations
// in anant_server/test/services/auth_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:anant_server/src/generated/protocol.dart' as _i2;
import 'package:anant_server/src/repositories/auth_repository.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:serverpod/serverpod.dart' as _i4;
import 'package:serverpod/src/cache/caches.dart' as _i5;
import 'package:serverpod_auth_server/module.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthKey_1 extends _i1.SmartFake implements _i3.AuthKey {
  _FakeAuthKey_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUuidValue_2 extends _i1.SmartFake implements _i4.UuidValue {
  _FakeUuidValue_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeServer_3 extends _i1.SmartFake implements _i4.Server {
  _FakeServer_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeServerpod_4 extends _i1.SmartFake implements _i4.Serverpod {
  _FakeServerpod_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDateTime_5 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabase_6 extends _i1.SmartFake implements _i4.Database {
  _FakeDatabase_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCaches_7 extends _i1.SmartFake implements _i5.Caches {
  _FakeCaches_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageAccess_8 extends _i1.SmartFake implements _i4.StorageAccess {
  _FakeStorageAccess_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMessageCentralAccess_9 extends _i1.SmartFake
    implements _i4.MessageCentralAccess {
  _FakeMessageCentralAccess_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_10 extends _i1.SmartFake implements Duration {
  _FakeDuration_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i6.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.User?> findUserByEmail(
    _i4.Session? session,
    String? email,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findUserByEmail,
          [
            session,
            email,
          ],
        ),
        returnValue: _i7.Future<_i2.User?>.value(),
      ) as _i7.Future<_i2.User?>);

  @override
  _i7.Future<_i2.User?> findUserByAnantId(
    _i4.Session? session,
    String? anantId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findUserByAnantId,
          [
            session,
            anantId,
          ],
        ),
        returnValue: _i7.Future<_i2.User?>.value(),
      ) as _i7.Future<_i2.User?>);

  @override
  _i7.Future<_i2.User?> findUserByAnantIdCaseInsensitive(
    _i4.Session? session,
    String? anantId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findUserByAnantIdCaseInsensitive,
          [
            session,
            anantId,
          ],
        ),
        returnValue: _i7.Future<_i2.User?>.value(),
      ) as _i7.Future<_i2.User?>);

  @override
  _i7.Future<_i2.User> createUser(
    _i4.Session? session,
    _i2.User? user,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [
            session,
            user,
          ],
        ),
        returnValue: _i7.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #createUser,
            [
              session,
              user,
            ],
          ),
        )),
      ) as _i7.Future<_i2.User>);

  @override
  _i7.Future<void> createCredentials(
    _i4.Session? session,
    _i2.UserCredentials? credentials,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCredentials,
          [
            session,
            credentials,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i2.UserCredentials?> findCredentialsByUserId(
    _i4.Session? session,
    int? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findCredentialsByUserId,
          [
            session,
            userId,
          ],
        ),
        returnValue: _i7.Future<_i2.UserCredentials?>.value(),
      ) as _i7.Future<_i2.UserCredentials?>);

  @override
  _i7.Future<_i3.UserInfo?> findAuthUserByIdentifier(
    _i4.Session? session,
    String? identifier,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findAuthUserByIdentifier,
          [
            session,
            identifier,
          ],
        ),
        returnValue: _i7.Future<_i3.UserInfo?>.value(),
      ) as _i7.Future<_i3.UserInfo?>);

  @override
  _i7.Future<_i3.UserInfo?> createAuthUser(
    _i4.Session? session,
    _i3.UserInfo? userInfo,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAuthUser,
          [
            session,
            userInfo,
          ],
        ),
        returnValue: _i7.Future<_i3.UserInfo?>.value(),
      ) as _i7.Future<_i3.UserInfo?>);

  @override
  _i7.Future<_i3.AuthKey> signInUser(
    _i4.Session? session,
    int? userId,
    String? method, {
    Set<_i4.Scope>? scopes = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInUser,
          [
            session,
            userId,
            method,
          ],
          {#scopes: scopes},
        ),
        returnValue: _i7.Future<_i3.AuthKey>.value(_FakeAuthKey_1(
          this,
          Invocation.method(
            #signInUser,
            [
              session,
              userId,
              method,
            ],
            {#scopes: scopes},
          ),
        )),
      ) as _i7.Future<_i3.AuthKey>);
}

/// A class which mocks [Session].
///
/// See the documentation for Mockito's code generation for more information.
class MockSession extends _i1.Mock implements _i4.Session {
  MockSession() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.UuidValue get sessionId => (super.noSuchMethod(
        Invocation.getter(#sessionId),
        returnValue: _FakeUuidValue_2(
          this,
          Invocation.getter(#sessionId),
        ),
      ) as _i4.UuidValue);

  @override
  _i4.Server get server => (super.noSuchMethod(
        Invocation.getter(#server),
        returnValue: _FakeServer_3(
          this,
          Invocation.getter(#server),
        ),
      ) as _i4.Server);

  @override
  _i4.Serverpod get serverpod => (super.noSuchMethod(
        Invocation.getter(#serverpod),
        returnValue: _FakeServerpod_4(
          this,
          Invocation.getter(#serverpod),
        ),
      ) as _i4.Serverpod);

  @override
  DateTime get startTime => (super.noSuchMethod(
        Invocation.getter(#startTime),
        returnValue: _FakeDateTime_5(
          this,
          Invocation.getter(#startTime),
        ),
      ) as DateTime);

  @override
  bool get isUserSignedIn => (super.noSuchMethod(
        Invocation.getter(#isUserSignedIn),
        returnValue: false,
      ) as bool);

  @override
  _i4.Database get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeDatabase_6(
          this,
          Invocation.getter(#db),
        ),
      ) as _i4.Database);

  @override
  _i5.Caches get caches => (super.noSuchMethod(
        Invocation.getter(#caches),
        returnValue: _FakeCaches_7(
          this,
          Invocation.getter(#caches),
        ),
      ) as _i5.Caches);

  @override
  Map<String, String> get passwords => (super.noSuchMethod(
        Invocation.getter(#passwords),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  _i4.StorageAccess get storage => (super.noSuchMethod(
        Invocation.getter(#storage),
        returnValue: _FakeStorageAccess_8(
          this,
          Invocation.getter(#storage),
        ),
      ) as _i4.StorageAccess);

  @override
  _i4.MessageCentralAccess get messages => (super.noSuchMethod(
        Invocation.getter(#messages),
        returnValue: _FakeMessageCentralAccess_9(
          this,
          Invocation.getter(#messages),
        ),
      ) as _i4.MessageCentralAccess);

  @override
  bool get enableLogging => (super.noSuchMethod(
        Invocation.getter(#enableLogging),
        returnValue: false,
      ) as bool);

  @override
  String get endpoint => (super.noSuchMethod(
        Invocation.getter(#endpoint),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#endpoint),
        ),
      ) as String);

  @override
  Duration get duration => (super.noSuchMethod(
        Invocation.getter(#duration),
        returnValue: _FakeDuration_10(
          this,
          Invocation.getter(#duration),
        ),
      ) as Duration);

  @override
  set userObject(dynamic value) => super.noSuchMethod(
        Invocation.setter(
          #userObject,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set storage(_i4.StorageAccess? value) => super.noSuchMethod(
        Invocation.setter(
          #storage,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set messages(_i4.MessageCentralAccess? value) => super.noSuchMethod(
        Invocation.setter(
          #messages,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addWillCloseListener(_i4.WillCloseListener? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #addWillCloseListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeWillCloseListener(_i4.WillCloseListener? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #removeWillCloseListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateAuthenticated(_i4.AuthenticationInfo? info) => super.noSuchMethod(
        Invocation.method(
          #updateAuthenticated,
          [info],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<int?> close({
    dynamic error,
    StackTrace? stackTrace,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
          {
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValue: _i7.Future<int?>.value(),
      ) as _i7.Future<int?>);

  @override
  void log(
    String? message, {
    _i4.LogLevel? level,
    dynamic exception,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #log,
          [message],
          {
            #level: level,
            #exception: exception,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );
}
